services:
  # Infrastructure services
  sqlserver:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1450:1433"
    restart: always
    volumes:
      - ticket_buddy_sql_server:/var/opt/mssql
    networks:
      - ticketbuddy-network
    profiles: ["infrastructure"]

  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    environment:
      - ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS:true
    ports:
      - "18888:18888"
      - "4317:18889"
    depends_on:
      - sqlserver
    networks:
      - ticketbuddy-network
    profiles: ["infrastructure"]

  rabbitmq:
    container_name: rabbitmq
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ticketbuddy-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["infrastructure"]

  # Event service components
  events-migrations:
    container_name: events-migrations
    build:
      context: .
      dockerfile: Events/Host.Migrations/Dockerfile
    depends_on:
      sqlserver:
        condition: service_started
    environment:
      - ENVIRONMENT=Development
    networks:
      - ticketbuddy-network
    restart: "no"
    profiles: ["event-service"]

  events-api:
    container_name: events-api
    build:
      context: .
      dockerfile: Events/Host.Api/Dockerfile
    depends_on:
      events-migrations:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
      aspire-dashboard:
        condition: service_started
    environment:
      - ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: on-failure
    networks:
      - ticketbuddy-network
    profiles: ["event-service"]

  events-api-outbox:
    container_name: events-api-outbox
    build:
      context: .
      dockerfile: Events/Host.Messaging.Outbox/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      sqlserver:
        condition: service_started
      aspire-dashboard:
        condition: service_started
      events-api:
        condition: service_started
    environment:
      - ENVIRONMENT=Development
    restart: on-failure
    networks:
      - ticketbuddy-network
    profiles: ["event-service"]

volumes:
  ticket_buddy_sql_server:
  rabbitmq_data:
  
networks:
  ticketbuddy-network:
    name: ticketbuddy-network
    driver: bridge
