services:
  sqlserver:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1450:1433"
    restart: always
    volumes:
      - ticket_buddy_sql_server:/var/opt/mssql
  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    environment:
      - ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS:true
    ports:
      - "18888:18888"
      - "4317:18889"
    depends_on:
      - sqlserver
  rabbitmq:
    container_name: rabbitmq
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  events-api:
    container_name: events-api
    build:
      context: .
      dockerfile: Events/Host.Api/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - aspire-dashboard
    environment:
      - ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: on-failure
  events-api-outbox:
    container_name: events-api-outbox
    build:
      context: .
      dockerfile: Events/Host.Messaging.Outbox/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - aspire-dashboard
      - events-api
    environment:
      - ENVIRONMENT=Development
    restart: on-failure

volumes:
  ticket_buddy_sql_server:
  rabbitmq_data: