# This is a generated file. Not intended for manual editing.
services:
  users-api:
    build:
      context: "C:\\Users\\seanj\\repos\\TicketBuddy"
      dockerfile: "Users/Users.Host.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/Users.Host.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "users.host.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\seanj\\repos\\TicketBuddy\\Users\\Users.Host.Api:/app:rw"
    - "C:\\Users\\seanj\\repos\\TicketBuddy:/src:rw"
    - "C:\\Users\\seanj\\AppData\\Roaming\\Microsoft\\UserSecrets:/home/app/.microsoft/usersecrets"
    - "C:\\Users\\seanj\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  users-messaging-outbox:
    build:
      context: "C:\\Users\\seanj\\repos\\TicketBuddy"
      dockerfile: "Users/Users.Host.Messaging.Outbox/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Users.Host.Messaging.Outbox.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "users.host.messaging.outbox:dev"
    ports: []
    volumes:
    - "C:\\Users\\seanj\\repos\\TicketBuddy\\Users\\Users.Host.Messaging.Outbox:/app:rw"
    - "C:\\Users\\seanj\\repos\\TicketBuddy:/src:rw"
    - "C:\\Users\\seanj\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  users-migrations:
    build:
      context: "C:\\Users\\seanj\\repos\\TicketBuddy"
      dockerfile: "Users/Users.Host.Migrations/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Users.Host.Migrations.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "users.host.migrations:dev"
    ports: []
    volumes:
    - "C:\\Users\\seanj\\repos\\TicketBuddy\\Users\\Users.Host.Migrations:/app:rw"
    - "C:\\Users\\seanj\\repos\\TicketBuddy:/src:rw"
    - "C:\\Users\\seanj\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
